{
	"version": 1530517146,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/stone-sheet0.png",
		"images/particles.png",
		"images/mountain_risk-sheet0.png",
		"images/mountain_risk2-sheet0.png",
		"images/food-sheet0.png",
		"images/big_boss-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/particles2.png",
		"images/particles3.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/particles4.png",
		"images/particles46.png",
		"images/title_page-sheet0.png",
		"images/start-sheet0.png",
		"images/points-sheet0.png",
		"images/load-sheet0.png",
		"images/hud_score_point-sheet0.png",
		"images/resume-sheet0.png",
		"images/pause-sheet0.png",
		"images/submit-sheet0.png",
		"images/dead-sheet0.png",
		"images/enemy_hud-sheet0.png",
		"images/bossy_bar-sheet0.png",
		"images/particles6.png",
		"images/eggs-sheet0.png",
		"images/story-sheet0.png",
		"images/high-sheet0.png",
		"images/save-sheet0.png",
		"images/note-sheet0.png",
		"images/menu-sheet0.png",
		"images/more_games-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"media/explosion 2.m4a",
		"media/explosion 2.ogg",
		"media/cancel - 5.m4a",
		"media/cancel - 5.ogg",
		"media/explosion 4.m4a",
		"media/explosion 4.ogg",
		"media/mattoglseby - 3.m4a",
		"media/mattoglseby - 3.ogg",
		"media/oops1.ogg",
		"media/oops1.m4a",
		"media/stratosphere.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}